### ISSUE TITLE
can't load my world after update

### ISSUE THREAD

**Issue by 47delasPECIIKOMODO** [TheIllusiveC4/Curios#100]
updated your mod and now i can't load my world
#### Versions (Be specific, do not write "latest"):
* Curios: curios-forge-1.16.4-4.0.3.4
* Forge 1.16.4-forge-35.1.36
#### Steps to Reproduce:
1.
2.
3.
...

Crash Log: Please use a paste site like [hastebin](https://hastebin.com/).
[debug.log](https://github.com/TheIllusiveC4/Curios/files/5810554/debug.log)
[latest.log](https://github.com/TheIllusiveC4/Curios/files/5810557/latest.log)
![Untitled](https://user-images.githubusercontent.com/77338081/104496360-8efed500-55e1-11eb-9bd6-eea23f5c9999.png)

**Comment by TheIllusiveC4** [comment]
You're loading up a lot of other mods as well, and there's nothing to indicate this is a Curios issue. Especially since I have not made any data pack changes in a long time. This seems to be an issue with either your data pack or your world itself. I'd suggest trying to redownload the modpack or, without another alternative, create a new world in order to resolve the issue.
