### ISSUE TITLE
Bug related to Enigmatic Legacy

### ISSUE THREAD

**Issue by LinJonKur** [TheIllusiveC4/Curios#122]
Hello! I'm using the mod Enigmatic Legacy and by what I understood it uses implementation provided on the side of Curios in order to give some accessories their Fortune/Looting increase abilities. When I have equipped a amulet with fortune every ore I mine gives coal instead of iron, redstone, lapis, etc. What can I do to solve this issue?

**Comment by TheIllusiveC4** [comment]
Please follow the bug template. I need at least all version numbers and reproductions steps without any other mods except for the ones involved.

**Comment by TheIllusiveC4** [comment]
I've had a chance to do some quick experimenting, and I cannot reproduce this issue. Gaining Fortune with Enigmatic Legacy allows me to mine Redstone Ore and get Redstone Dust as normal. Again, I'll need the information I asked above in order to isolate other mod incompatibilities. If you cannot reproduce this with only Curios and Enigmatic Legacy installed, then you'll need to investigate which mod is causing the issue.
