### ISSUE TITLE
Add Image and Label to slot

### ISSUE THREAD

**Issue by ClaudiusMinimus** [TheIllusiveC4/Curios#132]
As I have posted on your curseforge page and it seems you prefer questions to be posted here, I decided to ask you again.

curios-forge-1.16.5-4.0.5.1.jar
Forge 36.1.0

How do I add an image and a label to a custom slot? I have added a data pack for the slot and it works fine. I have also added a resource pack for the image using the same naming conventions you do in your mod, but it does not appear.

I would greatly appreciate your help regarding this matter.
Thank you,
CM

Below are screenshots of my directory structure and the curios slot in question. I use openloader for my data/resource packs which makes sure they are loaded for all those who use my pack.

![image](https://user-images.githubusercontent.com/17887664/116583632-c9ac2500-a8d3-11eb-866e-9b81d9f0c120.png)

![image](https://user-images.githubusercontent.com/17887664/116583177-4db1dd00-a8d3-11eb-81de-276b2a8b060e.png)

**Comment by TheIllusiveC4** [comment]
For the label, you need to add a translation file such as `en_us.json` to your resource pack and add a key for your slot.

For the image, this is a known issue that I'll need to address.

**Comment by ClaudiusMinimus** [comment]
I added the file `en_us.json` as follows and it worked perfectly!

`{
  "curios.identifier.magnet": "Magnet"
}`

Thanks,
CM

**Comment by ghost** [comment]
Ignore below, false alarm.

~~Hi, unfortunately, I'm having a similar slot texture issue. I use KubeJS to load in the tags, textures and lang, and the tags and lang work, but I'm not getting any textures:~~

![image](https://user-images.githubusercontent.com/24266948/121480436-6bb04880-ca0e-11eb-97ec-38a6364ac6fd.png)
![image](https://user-images.githubusercontent.com/24266948/121480489-79fe6480-ca0e-11eb-839f-ae4adb148ffa.png)
![image](https://user-images.githubusercontent.com/24266948/121480545-884c8080-ca0e-11eb-837a-df0952073d34.png)

~~P.S. How can I remove the default slots Curio adds on its own? I don't need a Charm slot, and didn't specify it in `curios-server.toml`, yet there it is.~~ I suspect this is actually caused by the charm slot being leftover in my playerdata in the world save. It is still a bit weird that the reset command didn't well... reset my slots and remove that charm slot.
