### ISSUE TITLE
[Feature Request] Keep Curios GUI open when toggling inventory

### ISSUE THREAD

**Issue by CREEATION** [TheIllusiveC4/Curios#138]
would work like the recipe book gui, where the gui remembers its state when closing the inventory and reopening it. 🐢

**Comment by Foozey** [comment]
Agreed with this. I think it would be a nice a feature.

**Comment by Foozey** [comment]
Better yet, make this feature configurable.

**Comment by ghost** [comment]
I completely agree.
A config to make the curios items always there would be amazing to skip clicking the little button, and doesn't sound like it would be hard to add since its already there but behind a button.

**Comment by TheIllusiveC4** [comment]
The premise of this suggestion seems to be based on the Curios GUI being more of a smaller component in a larger interface, like the Recipe Book GUI. However, the Curios GUI is an entirely separate screen (to avoid potential conflicts) that merely replicates the vanilla inventory screen. So there doesn't really exist a way to "toggle" it and have it remain in-state in the same way that the Recipe Book is coded.

In addition, the screen has a separate keybinding that can be used instead of the button if the desire is to skip straight to the Curios inventory. It could even, if one chose to do so, replace the vanilla inventory keybinding.
