### ISSUE TITLE
commands are explained badly

### ISSUE THREAD

**Issue by C4PTRAMPAGE** [TheIllusiveC4/Curios#143]
what is the full command syntax? because "/curios add head @a" doesn't work, also please show a full example command here https://github.com/TheIllusiveC4/Curios/wiki/Commands instead of just parts.

**Comment by TheIllusiveC4** [comment]
You'll have to be more specific when you say it "doesn't work". What does the error say? You've already gleaned the full command syntax, it's `/curios add head <player name>`. And there are in-game auto-completion suggestions for each command to help out as well.

**Comment by ghost** [comment]
I can confirm though (test environment, with only KubeJS and Curios installed) that custom slots setup via `curios-server.toml` cannot be removed with commands. You can remove new ones you add via commands, but you can't remove the existing ones. This issue is not present with default slots like "back" slots that were added with `curios-server.toml`.

* `Forge 36.1.16`
* `Curios (Forge) 4.0.5.2`
* `KubeJS (Forge) 1605.3.10-Build.18`

See #145 for how I've set up the custom slots.
