### ISSUE TITLE
Deobf Broken in 25

### ISSUE THREAD

**Issue by TheRealM18** [TheIllusiveC4/Curios#16]
#### Versions (Be specific, do not write "latest"):
* Curios: 25
* Forge: 101
#### Steps to Reproduce:
1. try using 25 in dev enviroment in 101 in single player
2.
3.
...

Crash Log: Please use a paste site like [hastebin](https://hastebin.com/).
https://pastebin.com/CXCSMNCe

**Comment by TheIllusiveC4** [comment]
This is because you're using different mappings in your development environment. In order to use any deobfuscated file, the mappings need to match. The mappings for version 0.25 are from MCP 20190901-1.14.3.

That being said, you really shouldn't be using the deobf file. Otherwise, your build might break whenever either of us update our mappings. It's only provided in case it's needed for whatever reason. You should be deobfuscating the jars yourself based off of the mappings in your build, like so:
```
dependencies {
    runtimeOnly fg.deobf("top.theillusivec4.curios:curios:${version}")
    compileOnly fg.deobf("top.theillusivec4.curios:curios:${version}:api")
}
```
