### ISSUE TITLE
[Forge 1.17.1] Client crash, when loading world

### ISSUE THREAD

**Issue by lays24mc** [TheIllusiveC4/Curios#167]
After updating to Forge 1.17.1 - 37.0.69 the client crashes when joining the world. With Forge 1.17.1 - 37.0.61 works the mod :)

#### Versions (Be specific, do not write "latest"):
* Curios: 1.17.1-5.0.10
* Forge/Fabric: Forge 1.17.1 - 37.0.69

Crash Log: https://hastebin.com/ofevifahac.rb

**Comment by Baggytrousers27** [comment]
Same as above (1.17.1 36.0.69). It's definitely an interaction with a mod because it seems to run with just curios and forge by itself (Can't open the curios menu obviously because no other mods to add slots but still).

[Crashlog](https://pastebin.com/FGzzpjqG) (With mods)

[Log without crash](https://pastebin.com/raPxqa0u)

**Comment by TheIllusiveC4** [comment]
I think this is related to a Forge bug. Can either of you two update to Forge 36.0.70 and verify if the bug still exists?

**Comment by lays24mc** [comment]
I have tested it with the 37.0.70 and can confirm that I can again join the world without errors :)

**Comment by Baggytrousers27** [comment]
That's done the trick. Cheers.
