### ISSUE TITLE
Example in 1.17.x doesn't reflect the 1.17.x changes.

### ISSUE THREAD

**Issue by mochamaple** [TheIllusiveC4/Curios#180]
Still getting a hang of the API, but from what I can tell example in the/1.17.x/src/test, despite having been moved out of the main mod still uses ICurio and ICurioItem, as well as depending on `import.top.theillusivec4.curios.common.capability.CurioItemCapability;` (which is in main)

Could it be updated to reflect the deprecated changes?

**Comment by TheIllusiveC4** [comment]
I'm not really sure what you mean, can you be more specific or rephrase your question?

As far as I can tell, there aren't any deprecated usages in the test classes. `ICurio` and `ICurioItem` have not been deprecated, just some of their methods. And I don't see any deprecated methods being used in the test classes. In addition, the major change of moving the rendering out of common code is present. I'm not sure where it doesn't reflect the changes in 1.17?

It is true that depending on `CurioItemCapability` is non-standard since it's an internal method, but all it does is make a basic capability provider instance and it is not any different than in 1.16.5 either.

**Comment by mochamaple** [comment]
My apologies as I think it's with me where the confusion lies. I misread the deprecation comment on the wiki, and I think I need to read up more on the internal methods code to fully understand CurioItemCapability.  To be clear does the test/ directory contain fully up to date 1.17.x compatible code?

**Comment by TheIllusiveC4** [comment]
> To be clear does the test/ directory contain fully up to date 1.17.x compatible code?

Yes. In the Curios development environment, the test mod is always run together with the main mod so it will always be compatible.
