### ISSUE TITLE
Config for keepinv

### ISSUE THREAD

**Issue by n0proxy** [TheIllusiveC4/Curios#181]
New feature request: 
A config option for determining whether you drop or keep items in your curio slots on death.

Why:
This setting might not be handled by the death mod someone uses. In my case, I don't have a good death mod for 1.17 but would still really like to allow my player's curio-worn backpacks and toolbelts to serve as 'important'/backup storage that stays with them on death.

(An API to allow death mods to hook in and offer to control this is additionally a useful idea!)

**Comment by TheIllusiveC4** [comment]
> (An API to allow death mods to hook in and offer to control this is additionally a useful idea!)

I believe that death mods do have all they need to incorporate Curios. Between the two events, `CurioDropsEvent` and `DropRulesEvent`, modders can hook into the drops and do whatever they want with them.

As for the main suggestion, I think this might make more sense as a game rule such as `keepCurios` in order to be in line with vanilla's own `keepInventory` game rule.

**Comment by ffuentesm** [comment]
Question, does Curios keep the curios items in their slots in death or not? 
Because I am playing now in 1.18.2 and the items are not staying on me. 
While in 1.18.2 they always stayed on me when I died. 
I am using most of the mods I had in my previous modpack.

**Comment by TheIllusiveC4** [comment]
That depends on the mods you use. Mods can decide whether or not their items are kept on death in Curios slots, and they can also affect other items as well if they choose.

By default, the drop behavior follows the `keepInventory` game rule.
