### ISSUE TITLE
Where can I equip the ring?

### ISSUE THREAD

**Issue by kands-code** [TheIllusiveC4/Curios#182]
I am a player in Minecraft, I used your mod and another mod that needs your mod. I encountered a problem when using the mod, that is, I found that I cannot equip the ring. Why is this?

This is my mod list

![图片](https://user-images.githubusercontent.com/59006329/143179847-c8ac67f9-23fb-409e-82a5-170d2378dab4.png)

This is my situation in the game

![图片](https://user-images.githubusercontent.com/59006329/143180064-5c5f1bdf-e426-4762-b839-2201c4c70e54.png)

![图片](https://user-images.githubusercontent.com/59006329/143180102-b262dc62-d67b-4710-8624-070668b0c49b.png)

Additional Infomation:
Forge Version: 36.2.19
Minecraft Version: 1.16.5
System: Archlinux
Launcher: Multimc5

**Comment by TheIllusiveC4** [comment]
The ring is normally an unobtainable item and does not have an associated slot enabled by default. It seems none of the mods you added add a ring slot, so you'll need to either just live with it or edit the configs as described [here](https://github.com/TheIllusiveC4/Curios/wiki/Pre-1.16-How-to-Use:-Users) in order to add your own ring slot.
