### ISSUE TITLE
1.18.1 Crash when breaking things in world using non-tools?

### ISSUE THREAD

**Issue by cpw** [TheIllusiveC4/Curios#199]
#### Versions (Be specific, do not write "latest"):
* Curios:1.18.1-5.0.4.1
* Forge/Fabric: 39.0.8
#### Steps to Reproduce:
1. Break a block with a non-tool in hand

Crash Log: Please use a paste site like [hastebin](https://hastebin.com/).

[crash-2021-12-25_12.17.33-server.txt](https://github.com/TheIllusiveC4/Curios/files/7776076/crash-2021-12-25_12.17.33-server.txt)
[crash-2021-12-25_12.20.28-server.txt](https://github.com/TheIllusiveC4/Curios/files/7776077/crash-2021-12-25_12.20.28-server.txt)

Two crash reports back to back.

Looks like the problem is that you're trying to reference `minecraft:this_entity` in your `curios.mixins.json:MixinApplyBonusCount` mixin, which doesn't seem to reliably exist and is thus crashing. It seems to reproduce fairly reliably.

**Comment by TheIllusiveC4** [comment]
Hmm, that's strange. This should've been fixed in the most recent update. I'm not even using the method that throws the `NoSuchElementException` anymore so I have no idea how that's still happening.

Are you able to reproduce this with only Curios? I'm having a bit of trouble reproducing this in my development environment.

**Comment by TheIllusiveC4** [comment]
The more that I look at this, the more it seems like the your instance is still running code from Curios version 5.0.4.0 for some reason despite the version saying 5.0.4.1. It's a strange conclusion and I very well could be missing something, but the stacktrace just doesn't make sense to me otherwise.

Could you try redownloading the 5.0.4.1 version of Curios and retrying?

Also, this is technically a duplicate so I'll be closing this but I'll be following up in the original issue:
https://github.com/TheIllusiveC4/Curios/issues/198
