### ISSUE TITLE
Trash slot, quark buttons, etc. disappearing after opening Curios window

### ISSUE THREAD

**Issue by Foozey** [TheIllusiveC4/Curios#201]
#### Versions (Be specific, do not write "latest"):
* Curios: 1.18.1-5.0.4.2
* Forge/Fabric: 1.18.1-39.0.9
#### Steps to Reproduce:
1. Open inventory
2. Open curios tab
3. Bye bye buttons

**Comment by TheIllusiveC4** [comment]
The mods that add extra buttons and such just need to add those buttons to the Curios GUI in addition to the vanilla one. For reference, it's not really a "tab" that Curios adds. It's a whole other screen that just mimics the vanilla one, which is why those other buttons will disappear if the compatibility isn't there.

**Comment by Foozey** [comment]
Yeah, I know it's not technically a "tab", I just used that term out of appearance. And thanks, I'll let them know.
