### ISSUE TITLE
Curios Items Disappear on a "Certain Server"

### ISSUE THREAD

**Issue by Subilan** [TheIllusiveC4/Curios#212]
#### Versions (Be specific, do not write "latest"):
* Curios: 1.16.5-4.0.6.8
* Forge/Fabric: 36.2.22
#### Steps to Reproduce:
Die in server running on **Mohist**. I am running a Mohist server with Curios, does it matter? I've heard that this behaviour **will only** appear on Mohist, but why? Any advice?

No crash happened.

**Comment by TheIllusiveC4** [comment]
I was not able to reproduce this behavior. Please update to the latest Curios (1.16.5-4.0.8.0) and try again. If it still happens, then it is likely a Mohist issue. I don't know why it would happen on Mohist because I do not know how Mohist works nor do I know how it interacts with any plugins you may have. I can only support Forge-only environments.

**Comment by Subilan** [comment]
Thanks.
