### ISSUE TITLE
[1.14.4] Mined a block in the Nether and crash.

### ISSUE THREAD

**Issue by Gbergz** [TheIllusiveC4/Curios#22]
#### Versions (Be specific, do not write "latest"):
* Curios: 1.0.0.3
* Forge: 28.1.20
#### Observed Behavior:
Mining an Ore in the nether (on a server)
#### Expected Behavior:
Mining as normal, ofcourse.
#### Steps to Reproduce:
1. Enter the nether
2. Mine an ore (dunno if its a specific ore)
3. Crash
...

Crash Log: Please use a paste site like [GistGithub](https://gist.github.com/Gbergz/c270def6751749410f6fca19ecc5dd14).

Note: this could be an EnigmaticLegacy issue but i'll report it here first. And see what you say.

**Comment by TheIllusiveC4** [comment]
I believe this is an Enigmatic Legacy issue and you should report it to them. Rather than mining, the issue seems to stem from experience drops. I believe this is crashing because Enigmatic Legacy hooks into experience drops [here](https://github.com/Extegral/Enigmatic-Legacy/blob/2ac2957665562979371bc3fe0cb04e7ef5259216/src/main/java/com/integral/enigmaticlegacy/handlers/EnigmaticEventHandler.java#L173) but doesn't first check to see if the attacking player is null, causing an NPE further down the stack.
