### ISSUE TITLE
Deleted Backpacks 

### ISSUE THREAD

**Issue by AngelTiramisu** [TheIllusiveC4/Curios#264]
I added this mod and it deleted eveyones MrCrayFish backpacks, do you know what i could do to recover these and the valuable items in them

**Comment by TheIllusiveC4** [comment]
Curios does not have any interaction on its end with MrCrayfish's Backpacked mod. If loading Curios causes the backpacks to be deleted from somewhere, that's likely going to be caused by Backpacked's Curios integration and you will need to report this to that developer instead for further investigation. They would also be the best person to ask for any workarounds and ways to recover your items as I'm not familiar with the mod myself.
