### ISSUE TITLE
World not loading when attempting to add a slot icon.

### ISSUE THREAD

**Issue by TERROR180** [TheIllusiveC4/Curios#268]
#### Versions (Be specific, do not write "latest"):
* Curios: forge-1.19.2-5.1.1.0
* Forge: 43.1.52
* Dynamic Lights: 1.19.2.1
* Radiant Gear (Forge): forge-2.0.0+1.19.2
#### Observed Behavior: World not loading with a message:
![Screenshot_20221109_102133](https://user-images.githubusercontent.com/117813714/200792420-d059a54f-4e30-4ee3-9496-2a42e059ad46.png)

#### Steps to Reproduce:
1.  Create a datapack to add a new slot called "light" in "datapacks\lights\data\curios\tags\items\light.json"
2. Create a resourcepack with the icon image in "light_slot_pack\assets\curios\textures\slot\Light_Slot.png"
3. Modify the "curios-server.toml" file as following:
![Screenshot_20221109_102200](https://user-images.githubusercontent.com/117813714/200793613-d1f93da0-607e-4ed2-ac83-81d1b1c1584a.png)
4. Turn on the game
5. Enable the resourcepack
6. Start the world

When removing the "icon" line from "curios-server.toml" world loads correctly, and everything functions properly, so I must've done something wrong with the resourcepack, though I have no idea what.

**Comment by TheIllusiveC4** [comment]
I'm not sure what's going on here, although from what you've described it does sound like some kind of issue with parsing the icon. Just taking a stab in the dark, can you try using all lowercase letters in the name of the image and try again?

If that doesn't work, can you please try to load up the world and then grab either the crash log or the `latest.log` file from that session so that I can look at what could be going wrong.

**Comment by TERROR180** [comment]
Did what you said, changed the name of the image to lowercase and did the same thing in the config file and, surprisingly, it worked! The image now displays correctly and everything loads perfectly fine. Thanks for the help!
