### ISSUE TITLE
Bug with bungeecord

### ISSUE THREAD

**Issue by BaptGosse** [TheIllusiveC4/Curios#272]
#### Versions:
* Curios: 1.16.5-4.0.5.3
* Forge/Fabric: 1.16.5 36.2.39
#### Steps to Reproduce:
1. Install last version of Lightfall, install mohist-1.16.5-1096-server and add Botania 1.16.5-420.2, patchouli 1.16.4-53.2 and curios 1.16.5-4.0.5.3 mods
2. Launch with Java JDK 15
3. Install Forge 1.16.5 36.2.39 in your computer and add Botania 1.16.5-420.2, patchouli 1.16.4-53.2, curios 1.16.5-4.0.5.3 and lightfall-client 1d4473d mods

Crash Log: https://hastebin.com/xejihowuwi.md

**Comment by TheIllusiveC4** [comment]
Unless this issue also occurs in a Forge-only environment, then this is likely an issue with Mohist or Bungeecord or how they interact together when loaded with Forge mods. There's nothing I can do about this on my end.

**Comment by BaptGosse** [comment]
I re open this issue because many others mods have bugs ! The problem is that bungeecord cannot correctly transmit your packets to mohist or that there is a problem and Bungeecord does not arrive. Several mods have managed to fix this like CustomNPC. It would be good if you could do the same please

**Comment by TheIllusiveC4** [comment]
CustomNPC is closed source so I cannot see what they may have done to address this. You would need to name a mod with a visible source, preferably with the exact commit that fixes the issue.

> The problem is that bungeecord cannot correctly transmit your packets to mohist or that there is a problem and Bungeecord does not arrive.

I'm not really sure what to do with this information because, from what I can tell, the instance is crashing because it cannot find the provider for Curios's command type. However, I don't even use packets or anything:
https://github.com/TheIllusiveC4/Curios/blob/dcb7ee3f3053facb141f2605612faa8f23493394/src/main/java/top/theillusivec4/curios/Curios.java#L117

I'm just registering it and letting the Forge/vanilla processes take it from there.
