### ISSUE TITLE
[1.14.4] /clear command doesn't clear Curios

### ISSUE THREAD

**Issue by comp500** [TheIllusiveC4/Curios#28]
#### Versions (Be specific, do not write "latest"):
* Curios: 1.14.4-1.0.5
* Forge: 1.14.4-28.1.70

#### Observed Behavior:
When I use /clear with a Curious Ring equipped, it says "No items were found on player comp500".

#### Expected Behavior:
/clear should remove the Curious Ring from my inventory.

#### Steps to Reproduce:
1. Add `createCurios = ["ring"]` to the curio-common.toml config
2. Create a creative singleplayer world
3. Get the Curious Ring, and equip it
4. Run the /clear command

Crash Log: N/A

**Comment by Extegral** [comment]
No. Don't do this. Don't take away that one method to clear inventory without all the curios being obliterated along. I would be very sad.

Although instead of keeping it as is, I would've offered to make the command clear everything, but the "destroy item" slot in creative inventory leave curios when Shift-clicked. Alternatively, it could be left as is, but with addition of new command to clear curios slots specifically.

In any case, that'd be quite inconvenient if there was no way to keep equipped curios while clearing everything within regular inventory.

**Comment by TheIllusiveC4** [comment]
@comp500 There's a command specific to Curios `/curios clear player [slot]`. Would that be good enough? Like mentioned above, I'm a little hesitant to remove all methods to specifically clear just the inventory or clear just the curios.

**Comment by comp500** [comment]
I see what you mean, I just expected `/clear` to clear the entire inventory and was surprised when it didn't. It's not an issue for me to have to use the specific command - I was just testing whether my mod worked properly when the curio was removed.
