### ISSUE TITLE
[1.19.2] Event Request

### ISSUE THREAD

**Issue by Shadows-of-Fire** [TheIllusiveC4/Curios#292]
**Please describe the new feature or change.**
The addition of a curios version of the `ItemAttributeModifierEvent`, which would allow for modifying the attribute modifiers of an item in a curio slot (whether or not the item implements `ICurio`).

**Please describe why you want this feature.**
Many people have requested that I add support for affixable curios in Apotheosis.  However, the primary affix class, attributes, relies on easy modification of attribute modifiers of an item, which is not currently possible for curios.
For normal items, this is possible through the `ItemAttributeModifierEvent`, which lets the attributes of any item be post-processed for any slot. A similar mechanism would need to exist for curios to be able to implement such support.

**Comment by lamoyrl90** [comment]
Here's a player's request for this PR being implemented

**Comment by TheIllusiveC4** [comment]
I've added a new event, `CurioAttributeModifierEvent`, to both 1.19.2 and 1.19.4. This event should work identically to the existing `ItemAttributeModifierEvent`, except using `SlotContext` instead of the vanilla equipment slot types. Let me know if there's anything amiss or if there's any additional features that you need to accommodate your use-case.
