### ISSUE TITLE
API download in China

### ISSUE THREAD

**Issue by Grey-Wind** [TheIllusiveC4/Curios#310]
Is there a mirror in China for the address downloaded during the construction of Curios API? Or if you can make the Chinese developer experience a little better, it's just not downloadable. 😭

**Comment by TheIllusiveC4** [comment]
I'm not familiar with the Chinese development process. Why is the address not downloadable? Do you have issues with downloading any other APIs? If not, do you know why it would be different for Curios?

**Comment by StarryFeatherRoKu** [comment]
I have the similar problem, it's difficult for Chinese developers to download foreign files directly because of the IP blocking in China

**Comment by TheIllusiveC4** [comment]
I'll need some suggestions for possible solutions, just detailing the problem isn't enough in this case because I am not familiar with the Chinese ecosystem.

Do other APIs from other developers have this issue? If not, how have they solved it? What are possible solutions to this that I could implement? Are you able to use VPNs to solve this?

Also, I would need some way to verify that any solution I implement actually works. Various tools that I've used online state that the Curios maven is not blocked in China, but that contradicts the testimony here, so I would need some other way to check any given solution or at least an explanation for the contradiction.

**Comment by IAALAI** [comment]
老兄，这个是因为libraries.minecraft.net之类的域名被封了吧。我近期也开始有这个问题，gradle构建必失败。试试看让gradle走代理就可以了。这个不是这个MOD的问题。我看社区也有人反应国际版正版无法登陆的

**Comment by Grey-Wind** [comment]
> 老兄，这个是因为libraries.minecraft.net之类的域名被封了吧。我近期也开始有这个问题，gradle构建必失败。试试看让gradle走代理就可以了。这个不是这个MOD的问题。我看社区也有人反应国际版正版无法登陆的

不是，我这里没有被封，别的都可以，就这个不行

很奇怪

**Comment by Grey-Wind** [comment]
> I'll need some suggestions for possible solutions, just detailing the problem isn't enough in this case because I am not familiar with the Chinese ecosystem.
> 
> Do other APIs from other developers have this issue? If not, how have they solved it? What are possible solutions to this that I could implement? Are you able to use VPNs to solve this?
> 
> Also, I would need some way to verify that any solution I implement actually works. Various tools that I've used online state that the Curios maven is not blocked in China, but that contradicts the testimony here, so I would need some other way to check any given solution or at least an explanation for the contradiction.

Can you set up a mirror site in China? I have not encountered this situation with other mods or apis.

**Comment by IAALAI** [comment]
你那情况比我好啊，我现在构建啥MOD都是失败。
每次自己构建都只能让gradle走镜像才编译成功
那要不然还是试试看让gradle走镜像？毕竟国内这个网络想搭一个镜像还是挺难的

**Comment by Grey-Wind** [comment]
> 你那情况比我好啊，我现在构建啥MOD都是失败。 每次自己构建都只能让gradle走镜像才编译成功 那要不然还是试试看让gradle走镜像？毕竟国内这个网络想搭一个镜像还是挺难的

难，我现在为了简单所以使用MCreator写基础，自己再写一些高级内容，综合一下导致很难改，MCreator那里改不了，Curios插件作者使用的就是Curios官方的站点

我这里情况好估计是因为在超一线城市，限制很小

**Comment by Grey-Wind** [comment]
> I'll need some suggestions for possible solutions, just detailing the problem isn't enough in this case because I am not familiar with the Chinese ecosystem.
> 
> Do other APIs from other developers have this issue? If not, how have they solved it? What are possible solutions to this that I could implement? Are you able to use VPNs to solve this?
> 
> Also, I would need some way to verify that any solution I implement actually works. Various tools that I've used online state that the Curios maven is not blocked in China, but that contradicts the testimony here, so I would need some other way to check any given solution or at least an explanation for the contradiction.

For Chinese developers, using a VPN is not recommended, and since Chinese law is vague about this and the government's judgment is more subjective, it would be better to have a smoother link.

Specifically Chinese mainland because of the recent vicious incident of being fined high by the government for using GitHub, the local government only relented after being pressured by public opinion.

For developers with less influence, using a VPN represents a risk or even jail time.

**Comment by TheIllusiveC4** [comment]
> For Chinese developers, using a VPN is not recommended, and since Chinese law is vague about this and the government's judgment is more subjective, it would be better to have a smoother link.
> 
> Specifically Chinese mainland because of the recent vicious incident of being fined high by the government for using GitHub, the local government only relented after being pressured by public opinion.
> 
> For developers with less influence, using a VPN represents a risk or even jail time.

I see, understandable then. Thank you for the insight.

However, the last part of my response still needs to be addressed. Various tools online for checking if a domain or website is blocked in China shows that the Curios maven should not be blocked and is fully accessible from China. However, two people, yourself including, in this thread state that's not the case. I would link the tools here, but I'm unsure if you can view them safely.

If I am to implement any sort of solution, I would ideally be able to verify myself that it works. In addition, I don't have any way, currently, to verify that this is actually a domain block issue or if it's just an isolated problem with specific developers for some reason because the tools state one thing and the testimony in this thread state another.

> Can you set up a mirror site in China? I have not encountered this situation with other mods or apis.

Maybe, but I don't know how to do that at this time. And this goes back up to my previous point, I would need a way to check that setting up such a site actually works once I've done so without relying on just testimony.

That all being said, I am planning on setting up a whole new maven at some point to replace the current one and I'll try to keep this testimony in mind during that process.
