### ISSUE TITLE
How to add two ring slot (curios-forge-5.2.0-beta.1+1.20)

### ISSUE THREAD

**Issue by Samlegamer** [TheIllusiveC4/Curios#313]
Hello, I've seen the new slot system which now uses datapacks but when I want to add 2 ring slots the game only displays one: 
```
{
  "entities": ["player"],
  "slots": ["ring", "ring"]
}
```

**Comment by TheIllusiveC4** [comment]
That's the entity configuration file, which is only for giving already registered slot types and doesn't stack like that. What you want to do is create a ring slot datapack file and specify `"size": 2` in order to change the number of slots for that slot type. I'll update the documentation to clarify this point.

**Comment by Samlegamer** [comment]
I saw that you what you have added and I understand better the principle thank you to you!
