### ISSUE TITLE
Mismatch between the docs and the actual mod

### ISSUE THREAD

**Issue by ofek2608** [TheIllusiveC4/Curios#315]
#### Versions (Be specific, do not write "latest"):
* Curios: 5.2.0-beta.3+1.20.1
* Forge/Fabric: forge
#### Observed Behavior:
Using data to register slot on a custom namespace does nothing.
#### Expected Behavior:
Register a slot type, as seen in the docs
https://docs.illusivesoulworks.com/curios/slot-register#directory
#### Steps to Reproduce:
Create a file data/example/curios/slots/myslot.json with the config
Then it doesn't appear in the game.

after looking a bit in the sources, seems like CuriosSlotManager filters only curios slots with namespace "curios"
https://github.com/TheIllusiveC4/Curios/blob/1.20.x/src/main/java/top/theillusivec4/curios/common/data/CuriosSlotManager.java#L50

**Comment by TheIllusiveC4** [comment]
> Create a file data/example/curios/slots/myslot.json with the config
Then it doesn't appear in the game.

Did you follow the follow-up instructions on [adding a slot type to the player/entity](https://docs.illusivesoulworks.com/curios/entity-register)? Otherwise, the slot exists but is not assigned to anything.

> after looking a bit in the sources, seems like CuriosSlotManager filters only curios slots with namespace "curios"
https://github.com/TheIllusiveC4/Curios/blob/1.20.x/src/main/java/top/theillusivec4/curios/common/data/CuriosSlotManager.java#L50

This section of the code processes slots in the Curios namespace _first_, you can see later it processes the rest as well: https://github.com/TheIllusiveC4/Curios/blob/a3cb4324f4522f8529e3a5aaaf6b04d40a739ff4/src/main/java/top/theillusivec4/curios/common/data/CuriosSlotManager.java#L78-L95

**Comment by ofek2608** [comment]
Hey, sorry, no i didn't i guess i rushed a bit to the bug reports. thanks, and sorry.
