### ISSUE TITLE
Question: ?

### ISSUE THREAD

**Issue by SteelTigerV2** [TheIllusiveC4/Curios#326]
what is the inventory slot numbers for curios gear ?

**Comment by TheIllusiveC4** [comment]
Technically, the slot numbers are indices 46 and up depending on the number of slots. However, this is susceptible to change depending on if any other mod injects its own slots into the inventory. In addition, be wary of trying to manipulate the contents of Curios using these slot indices because Curios uses its own internal inventory rather than vanilla inventories.
