### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Serzh812** [TheIllusiveC4/Curios#36]
can't do it [https://github.com/TheIllusiveC4/Curios/wiki/How-to-Use:-Users](url)
items are not inserted
perhaps a simple working example ?

**Comment by TheIllusiveC4** [comment]
I outline a simple working example using eggs in the wiki guide. You'll have to provide more details about what's not working and what you're trying to achieve. In addition, you'll need to show your config file and the data pack json files that you made.

**Comment by Serzh812** [comment]
slot there is-subject not insert
[https://mega.nz/#!ixd2hYBY!Nsj-pQoj0Id1mokKud9ioi-HAQOcGfnn6p7UUE_XDr4](url)

**Comment by TheIllusiveC4** [comment]
Your settings work for me. 

It looks like your tag isn't being recognized on your end. Did you make sure that your folder structure is like `.minecraft/saves/(world-name)/datapacks/(datapack-name)/data/curios/tags/items`? And that `pack.mcmeta` is in the `(datapack-name)` folder?

**Comment by Serzh812** [comment]
all files in their places
p.s. installed portable minecraft
folder ".minecraft" is called "nativ...."

**Comment by TheIllusiveC4** [comment]
Are you sure the files are in the right places? Because your tag isn't being recognized and I saw that the way your folder was organized in the zip that you sent me above was incorrect. For instance, the `data` folder was inside the `datapacks` folder and not inside its own `(datapack-name)` folder. As long as the file structure is correct, your settings will work because they work for me. I can put the wood jetpack into the created slot.

I'm not sure if it being a portable Minecraft affects it or not. If it does, then it's not something I can really help with since this is just leveraging the vanilla data pack feature. 

Also, just in case, I'd like to mention that even if you do get inserting the jetpack into the slot working, the jetpack won't function like it does in the armor slot because it wasn't coded to support curios functionality.

**Comment by Serzh812** [comment]
files created correctly?

**Comment by Serzh812** [comment]
submit your file structure

**Comment by TheIllusiveC4** [comment]
Your config files should be fine as long as you put them in the config folder, so I'll just send my version of the `datapacks` folder.
[datapacks.zip](https://github.com/TheIllusiveC4/Curios/files/3945748/datapacks.zip)

**Comment by Serzh812** [comment]
ОК
thank you very much

**Comment by Serzh812** [comment]
last question
how to insert any Jetpacks

**Comment by TheIllusiveC4** [comment]
You do the same thing you did with the wood jetpack. Put the item name in the `jack.json` item tag file. You'll need to do this for each jetpack.

**Comment by Serzh812** [comment]
thank you very much
