### ISSUE TITLE
[Bug]: Curios Inventory Keybind exits out of Flux Netowrk text boxes while typing.

### ISSUE THREAD

**Issue by PlayfulPiano** [TheIllusiveC4/Curios#360]
### Minecraft Version

1.20.1

### What happened?

While trying to rename a flux plug from Flux Networks, whenever I hit "E" (which is what I have the curios inv keybind set to), it will exit out of the GUI, even though I have the text box selected.

### How do you trigger this bug?

1. Set curios keybind to E.
2. Try typing a word with the letter "e" in it within a Flux networks text box.
3. GUI closes.
...

### Loader

Forge

### Loader Version

47.2.16

### Mod Version

5.4.5-1.20.1

**Comment by TheIllusiveC4** [comment]
I'm not 100% sure on this but this may need to be reported to Flux Networks for further investigation instead. Other uses of typing in GUIs, like renaming items in the anvil, allow the Curios keybind to be typed as expected but this is not the case for the Flux Networks GUI. This may be caused by something specific to how they're handling their GUIs and I'm not sure if this is fixable on my end.

**Comment by PlayfulPiano** [comment]
Got it, will do.
