### ISSUE TITLE
[Bug]: Doubling items with the keepinventory true command.2 slots for some items and 5 ring slots.

### ISSUE THREAD

**Issue by Sadamlucien** [TheIllusiveC4/Curios#365]
### Minecraft Version

1.20.1

### What happened?

I have a problem that when I change the status of the keepinventory command to True, all items placed in additional slots appear in the inventory after death, while remaining in the inventory.

I found out that the problem is in one of the installed mods, because leaving only Botania, the slots were less and this problem did not occur.
![unknown_2024 01 09-12 57_2](https://github.com/TheIllusiveC4/Curios/assets/156078695/48ca54ae-903c-4cd8-9c0e-d11d4af14bdb)
![unknown_2024 01 09-12 57](https://github.com/TheIllusiveC4/Curios/assets/156078695/5004b3d7-0fe3-4686-8edf-bc9e6d1c6cbd)
![unknown_2024 01 09-12 57_1](https://github.com/TheIllusiveC4/Curios/assets/156078695/9066e943-9860-41ea-95be-811b5f9c27a1)
![unknown_2024 01 09-12 57_3](https://github.com/TheIllusiveC4/Curios/assets/156078695/282a69cb-9aff-4c6a-be51-a1547088c3e5)

I am unable to find the source of this problem. Here is the modpack on which I play on

### How do you trigger this bug?

1.
2.
3.
...

### Loader

Forge

### Loader Version

Forge 47.2.19

### Mod Version

Curios 5.4.7

**Comment by TheIllusiveC4** [comment]
You'll need to discover which mod is the source of the problem if this is a mod conflict. I can't investigate further without knowing where the problem originates from. You can begin isolating candidates by taking your mod list and eliminating half of the mods at a time and see which half still has the issue, and then repeating the process until a candidate has been found.

**Comment by Thib1000** [comment]
Hi, I had the same problem so I analized your screens and I tested all mods we have in common.
So, the only mod that causes this problem is DivineRPG
I even tried to solve this problem and I found out that one settings in DivineRPG config fixes it.
You just have to put "saferVetheanInventory" to "true" and it will work just fine (Image)
Sorry for my english, I am speaking french for my main language
![image](https://github.com/TheIllusiveC4/Curios/assets/102856480/c54701ae-1e4b-4336-b17a-19989c70d2f2)
