### ISSUE TITLE
nest item[Bug]: 

### ISSUE THREAD

**Issue by sus2221** [TheIllusiveC4/Curios#369]
### Minecraft Version

1.19.2

### What happened?

It says to me that you can insert a ruby ​​into an object, but I can’t how to insert it?

### How do you trigger this bug?

1.
2.
3.
...

### Loader

Forge

### Loader Version

Newest

### Mod Version

5.1.5.0

**Comment by TheIllusiveC4** [comment]
I don't know which ruby or item you're referring to, but this sounds like a different mod because Curios doesn't add anything like that. Please report this issue to the mod which developed the item(s) that you're referencing. If this isn't a different mod, then please attach a screenshot of what you're referring to.
