### ISSUE TITLE
[Bug]: Crash when rendering tooltip of some unknown item (possibly The Aether's "Gloves") as of v5.7.1

### ISSUE THREAD

**Issue by unilock** [TheIllusiveC4/Curios#388]
### Minecraft Version

1.20.1

### What happened?

When rendering the tooltip of one of the items in-game - I'm not sure *which* item, as the game crashes before I can see it - the game crashes with a NPE.

It seems to be related to https://github.com/TheIllusiveC4/Curios/commit/38bee4cc5431d9faffa094ecdad180d2e015eed5.

I apologize in advance: I didn't go through my very large mod set to narrow down which mod is causing the issue, as that would take ages, and I'm hoping this is as simple as a missing null check...

EDIT: After downgrading Curios to 5.7.0, which works fine, I'm lead to believe the item(s) causing the issue are the equipable "Gloves" from [The Aether](https://modrinth.com/mod/aether).

### How do you trigger this bug?

1. View the tooltip of an item that causes this bug
2. Game crashes with a NPE

### Loader

NeoForge

### Loader Version

47.1.100

### Mod Version

5.7.1+1.20.1

### Relevant Log Outputs

Crash report: https://gist.github.com/unilock/3bb69173cd96d32d325a622bb29c6d72

**Comment by uhloin** [comment]
When I use JEI, open inventory and hover on JEI right panel, then have an error message instead of tooltip like "Tooltip error, go to logs", but there are nothing in logs. After some short time game stops responding or crashed without dump.

This problem is for "curios-forge-5.7.1+1.20.1.jar" and all OK with "curios-forge-5.7.0+1.20.1.jar"

**Comment by uhloin** [comment]
And about Aether Gloves, I have it too, but it was OK, until this update. The Aether mod has its own curiuos-like menu? So conflicts are possible? But I just tried to update to 5.7.1 but remove Aether. No crush after 5 min of gameplay, but I still have tooltip error even without Aether.

**Comment by TheIllusiveC4** [comment]
I can see where the problem is coming from, but I don't know what's causing it and it seems likely that it's a rather specific mod conflict. Since I have trouble reproducing this, I've attached a build of the mod with a potential fix:

[curios-forge-5.7.2+1.20.1-snapshot20240311.zip](https://github.com/TheIllusiveC4/Curios/files/14561756/curios-forge-5.7.2%2B1.20.1-snapshot20240311.zip)

Can one or both of you try this out and report back whether it resolves the reported issues?

**Comment by uhloin** [comment]
Thank you for so quick reaction. I tested this .jar together with Aether mod, and now tooltips are OK. Also, I re-created and wear gloves. I will leave this Minecraft World running to ensure it will not crash after some time.

Update: no crash after 1 hour

**Comment by unilock** [comment]
> Can one or both of you try this out and report back whether it resolves the reported issues?

That build does seem to have fixed the crash for me as well :)
