### ISSUE TITLE
Ablity to pick & choose which Curios are rendered.

### ISSUE THREAD

**Issue by MLMII** [TheIllusiveC4/Curios#43]
**Please describe the new feature or change.**

I was wondering if it were possible to have an option to choose which curios were rendered instead of an universal option in the config.

**Please describe why you want this feature.**

Some curios are nicely rendered on my Minecraft skin, but some feel out of place.

Thank you.

**Comment by TheIllusiveC4** [comment]
Yeah, I've been very interested in implementing this feature. I just have to think of the right way to implement it.

**Comment by ItsTheBdoge** [comment]
Could you add a button on the side of each curios slot which toggles its rendering? similar to how terraria does this

**Comment by zlainsama** [comment]
@TheIllusiveC4 
Any updates on this?
I have released CosmeticArmorReworked 1.15.2-v3a in beta which added toggleable buttons to Curios slots like I did with Baubles in 1.12.2. ([A link if you are interested](https://github.com/zlainsama/CosmeticArmorReworked/releases/tag/1.15.2-v3a))
Currently, I am using reflections and constantly checking if scroll index has changed to update those added buttons.
Since the implementation I have done is quite dirty, I would like an official way of doing this stuff without worrying it broken in Curios internal changes, and safely back out if Curios have this feature implemented in the future.

**Comment by TheIllusiveC4** [comment]
I'd like to implement this when I have the design space to rewrite whatever I may need, so I'm waiting until I port Curios to 1.16+ to add this feature. It'll be a native feature to the GUI and my current idea will end up looking a lot similar to what you've set up in Cosmetic Armor Reworked with the toggle-able button in the corner.

**Comment by TheIllusiveC4** [comment]
Toggleable renders have been added to the 1.16.1 port.
