### ISSUE TITLE
Crash when using Mahou Tsukai's scrying

### ISSUE THREAD

**Issue by stepsword** [TheIllusiveC4/Curios#77]
Hi, a player sent me this crash log which I think could be fixed by a null check somewhere in this mod? Let me know if that's not the case

Crash Log: https://pastebin.com/9frFDh0y

**Comment by TheIllusiveC4** [comment]
I see that it's caused by activating something called `ScryingMahoujinTileEntity`. Could you describe what that is and how to replicate it in-game? I'm unfamiliar with the Mahou Tsukai mod. You are correct in that the problem probably can be solved by adding a null check on my end, but I'd like to know how to replicate the behavior for testing/debugging purposes.

**Comment by stepsword** [comment]
According to the user, he was using the scrying spell on another player on a server - I couldn't replicate it in single player and I don't have a non-dev server to test currently, so keep that in mind..

But in general, to use scrying:

0. Get enough mana by running the command `/maxmahou player_name 10000` in creative mode or as someone with permissions
1. Take damage (can be done by right clicking with the purple Dagger)
2. Press M to draw a magic circle with blood
3. Right click with Powdered Ender on the circle
4. Right click again with another Powdered Ender on the circle
5. Right click with Powdered Eye on the circle
6. Use a nametag in an anvil and put a player's name in it
7. Drop the nametag on top of the circle.
8. If successful, a small render of the player will appear on top of the circle along with their surroundings
