### ISSUE TITLE
[1.16.3 Fabric] Curio slots not appearing.

### ISSUE THREAD

**Issue by rgilbert1021** [TheIllusiveC4/Curios#81]
#### Versions (Be specific, do not write "latest"):
* Curios: curios-fabric-0.0.8-1.16.3
* Fabric: fabric-api-0.23.0+build.410-1.16
#### Steps to Reproduce:
1. Checked out repo, ran application.
2. After loading into the world attempted to click the curio button and use the keybind.
3. Expected curio slots to show up, but they didn't.
4. Gave myself all of the curios and attempted to right click equip them, but none of them worked.

No errors were present in the console or in the debug logs.

**Comment by TheIllusiveC4** [comment]
Which curio slots do you expect to appear?
In other words, which mods do you have create slots and what slots do they create? Alternatively, what slots have you configured in the config file?

**Comment by elowanut** [comment]
Installing Curios gives you the framework (backend code, the button / keybind, the framework for the slots themselves) for curios slots, but by default none of the slots are active. This is so that individual mods that add slots can add them in as needed; if you install only a mod that adds necklaces, that mod can just turn on the necklace slot, and not have a whole bunch of empty, unusable slots.

You need to test curios in conjunction with a mod that depends on / uses it, or you will see the button next to your portrait, but the keybind won't open any slots.

**Comment by rgilbert1021** [comment]
Sorry for the erroneous report.  Could have sworn in the past that the included curios auto registered and were available to use.
