### ISSUE TITLE
A way to allow Curse of Binding on accessories

### ISSUE THREAD

**Issue by Aizistral** [TheIllusiveC4/Curios#87]
**Please describe the new feature or change.**
A way to allow Curse of Binding on accessories, again preferrably by simple flag method in `ICurio` interface.

**Please describe why you want this feature.**
It's currently difficult to pull off, since Curse of Binding is hardcoded to only allow to apply itself to armor. It is again possible with the use of Mixin, and having it implemented on the side of Curios would reduce redundant mixins mod developers would have to create in order to achieve this. This suggestion however suffers from the same nuances as outlined in #86, and even both combined don't seem to be significant enough features to start using Mixin with inconveniences taken into account, so this idea either will probably have to float around until some other time.

**Comment by TheIllusiveC4** [comment]
I know it's been a while since this suggestion was stated, but it's finally time to come back to this now that mixins have formally been introduced to Curios in 1.18.1.

That said, I'm not sure if we discussed this before, but it seems like Curse of Binding can already work on accessories as long as they implement the `Wearable` (Mojmap) or `IArmorVanishable` (MCP) interfaces. And implementing these interfaces doesn't seem to have any other side-effects. The only problem then is that you would not be able to apply them to items your mod does not own, which comes with a lot of caveats about how easy/difficult it is to accomplish since I don't see any good entrypoints to do that, even through mixins.

All in all, I'd like to ask what issue I may have missed in my observations, if anything, and what the specific solution would be?

**Comment by Aizistral** [comment]
Either things have changed from how they have been 1.16.1-1.16.3, or I somehow completely glossed over the fact that it actually checks by interface. Anyhow, with that in mind I no longer think it makes sense to do anything about compatibility with this curse on the side of Curios, and thus withdraw my suggestion.
