### ISSUE TITLE
Shift-Click Curios into their slots even when not on screen

### ISSUE THREAD

**Issue by aaronhowser1** [TheIllusiveC4/Curios#94]
#### Versions (Be specific, do not write "latest"):
* Curios: curios-forge-1.16.4-4.0.3.0
* Forge/Fabric: forge
#### Observed Behavior:
![image](https://user-images.githubusercontent.com/15698722/101602130-3bd2aa80-39c3-11eb-9d4d-06b8c9461b84.png)
shift clicking does nothing
![image](https://user-images.githubusercontent.com/15698722/101602148-43924f00-39c3-11eb-89e9-ce743ece1224.png)
shift clicking makes it enter the statues slot
#### Expected Behavior:
it should enter the slot if its visible or not

**Comment by Aizistral** [comment]
I would say that is to be expected, granted invisible slots technically do not exist at all as part of inventory, but if it worked that way it would make some sense either.

**Comment by TheIllusiveC4** [comment]
This is more of a feature request than a bug because it's working exactly as intended. It's a little trickier than it seems because, to make this feature, I need to not only allow the technical ability to move an item into any available slot but also provide some feedback to the user that this was done. This is because it's a little weird if a user accidentally shift-clicks an item they didn't know could go into a Curios slot and then it suddenly disappears and they don't know what happened. Thus, I need to think about a proper implementation for this.

**Comment by ochotonida** [comment]
Perhaps you could move the scroll bar when shift clicking such that the item is still on screen afterwards?

**Comment by TheIllusiveC4** [comment]
This feature has been included in the new GUI introduced in 1.20.1 and 1.20.4+.
