### ISSUE TITLE
Status Effects with Curious Interface

### ISSUE THREAD

**Issue by Mike-U5** [TheIllusiveC4/Curios#95]
Currently, status effects do not show up on the hud with the Curio interfaces open. It would be helpful if it did.

**Comment by Calibrumm** [comment]
just want to bump this feature. no rush but switching from Curios to normal inv to check status can be annoying.

**Comment by LordFreyr** [comment]
I came here to post the same thing. Wasn't entirely sure if it was intentional or not, but it would be nice to be able to see potion effects/etc. on the side of the curios GUI like they appear in the regular inventory. Could even make it display the same way it would if you have the crafting book open.
I'd just like to be able to check statuses from there as I tend to replace my regular inventory keybind with the Curios one.
